<?php

function getDevelopers()
{
    $developers = [
        "Abou Eid",
        "Allegiance",
        "Al Zorah",
        "AMIS",
        "Arada",
        "Azizi",
        "Bali Developers",
        "Beyond",
        "Binghatti",
        "City Developers",
        "Citi",
        "Danube",
        "Dar Alkarama",
        "DE Address DHE B-5-512",
        "Deca",
        "Devmark",
        "Deyaar",
        "DMCC",
        "Dubai Properties",
        "Durar",
        "Damac",
        "Emaar",
        "Evolutions",
        "Fakhruddhin",
        "Fam Properties",
        "Gemini",
        "Ginco Properties",
        "Heart of Europe",
        "HRE",
        "Iman",
        "Imtiaz",
        "LEOS",
        "London Gate",
        "Majid Al Futtaim",
        "ME DO RE",
        "Meraas",
        "Nabni",
        "Nakheel",
        "Nshama",
        "Object 1",
        "Octa",
        "Omniyat",
        "Oro24",
        "Prestige",
        "Prestige One",
        "Prescott",
        "RAK",
        "RAK Properties",
        "Range",
        "Reportage",
        "RSG",
        "Samana",
        "Secondary",
        "SRG",
        "Sobha",
        "SOL",
        "Tabeer",
        "Tiger",
        "Vincitore",
        "Zoya"
    ];

    return $developers;
}
