<?php

function getDevelopers()
{
    $developers = [
        "Heart of Europe",
        "Secondary",
        "Danube",
        "Devmark",
        "Arada",
        "Aldar",
        "Azizi",
        "SOL",
        "RAK Properties",
        "RSG",
        "London Gate",
        "Damac",
        "Sobha",
        "Oro24",
        "Meraas",
        "Prestige",
        "Octa",
        "AMIS",
        "Emaar",
        "Nabni",
        "Reportage",
        "Nakheel",
        "Vincitore",
        "SRG",
        "Tabeer",
        "Iman",
        "Prestige One",
        "Tiger",
        "Dubai Properties",
        "Al Zorah",
        "Gemini",
        "Deyaar",
        "Range",
        "Imtiaz",
        "Omniyat",
        "Al Marina",
        "Abou Eid",
        "Citi",
        "Fam Properties",
        "RAK",
        "Ellignton",
        "City Developers",
        "Deca",
        "Object 1",
        "Samana",
        "Dar Alkarama",
        "Fakhruddhin",
        "Durar",
        "Evolutions",
        "Peak Summit",
        "Majid Al Futtaim",
        "Nshama",
        "LEOS",
        "DE Address DHE B-5-512",
        "Ginco Properties",
        "Bali Developers",
        "Binghatti",
        "DMCC",
        "Allegiance",
        "Prescott",
        "HRE",
        "Beyond",
        "Zoya",
        "ME DO RE"
    ];

    return $developers;
}
